REDDIT_API_CLIENT_ID = "iyF1UTpekLp_ukaIpyMylA"
REDDIT_API_CLIENT_SECRET = "5Pm624LqQWSxc-kbOCptAW8c8BAL_A"
REDDIT_API_USER_AGENT = "chustiy"


#{
#"REDDIT_API_CLIENT_ID" : "iyF1UTpekLp_ukaIpyMylA",
#"REDDIT_API_CLIENT_SECRET" : "5Pm624LqQWSxc-kbOCptAW8c8BAL_A",
#"REDDIT_API_USER_AGENT" : "chustiy",
#}